function Write-MFSectionIndex
{

    <#
        .SYNOPSIS
            Write a Just The Docs parent index page with front matter and an auto-generated child link list.

        .DESCRIPTION
            Creates or overwrites a markdown file at FilePath with a YAML front matter block containing
            'layout', 'title', optional 'parent', and 'has_children: true'. Appends an H1 heading and
            the supplied child link list as the page body.

        .NOTES
            Author: Adrian Andersson
    #>

    [CmdletBinding()]
    [Diagnostics.CodeAnalysis.SuppressMessage("PSUseSingularNouns", "", Justification = "Writes a single index file for a docs section")]
    PARAM(
        #Full path where the index.md file should be written
        [Parameter(Mandatory,ValueFromPipeline,ValueFromPipelineByPropertyName)]
        [string]$FilePath,
        #Navigation title for this section (used in 'title:' and H1)
        [Parameter(Mandatory)]
        [string]$Title,
        #Parent nav title. Omit for depth-1 sections.
        [Parameter()]
        [string]$Parent,
        #Markdown bullet list lines generated by Get-MFChildLinkList
        [Parameter()]
        $ChildLinks
    )
    process{
        $lines = [System.Collections.Generic.List[string]]::new()
        $lines.Add('---')
        $lines.Add('layout: default')
        $lines.Add("title: $Title")
        if($Parent){ $lines.Add("parent: $Parent") }
        $lines.Add('has_children: true')
        $lines.Add('---')
        $lines.Add('')
        $lines.Add("# $Title")
        $lines.Add('')
        if($ChildLinks)
        {
            foreach($link in $ChildLinks){ $lines.Add($link) }
        }
        $lines -join "`n" | Out-File $FilePath -Force
    }
}